name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    env:
      MESSAGE: Hola mundo

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4
        
      - name: Working dir afetr action
        run: ls -al
        
  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"