name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
        
  second-job:
    if: false
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"