name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    outputs:
      message: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
        
  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ needs.first_job.outputs.message }}

    steps:
      - name: Hola mundo
        run: echo "$MESSAGE"