name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
        
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"
      - name: Ver valor contexto
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Value github.ref = ${{ github.ref }}"