name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hola mundo

    steps:
      - name: Hola mundo
        run: echo "$MESSAGE"
        
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"