name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate file
        run: |
          echo "Test file, hello" >> test.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-test-log
          path: test.log

  second_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: file-test-log
          
      - name: Cat file
        run: cat test.log